import { buildAudit } from "@/lib/buildAudit";

export const seededAudits = [
  buildAudit({
    businessName: "Clearflow Plumbing",
    city: "Riverside, CA",
    industry: "Plumbing",
    websiteStatus: "exists-but-outdated",
    mobileFriendly: false,
    loadsFast: false,
    hasSsl: true,
    gbpClaimed: true,
    gbpHours: false,
    gbpPhotos: false,
    gbpDescription: false,
    gbpPrimaryCategory: true,
    hoursAccurate: false,
    phoneAccurate: true,
    addressAccurate: true,
    servicesAccurate: false,
    averageRating: 3.8,
    reviewCount: 7,
    mapsTopThree: false,
    clickToCall: true,
    quoteForm: false,
    repliesFast: false
  }),
  buildAudit({
    businessName: "Mama Lina's Kitchen",
    city: "Long Beach, CA",
    industry: "Restaurant / Food Service",
    websiteStatus: "exists-but-outdated",
    mobileFriendly: true,
    loadsFast: false,
    hasSsl: true,
    gbpClaimed: true,
    gbpHours: true,
    gbpPhotos: false,
    gbpDescription: false,
    gbpPrimaryCategory: true,
    hoursAccurate: false,
    phoneAccurate: true,
    addressAccurate: true,
    servicesAccurate: false,
    averageRating: 4.1,
    reviewCount: 18,
    mapsTopThree: false,
    menuAccurate: false,
    deliveryAppsListed: true,
    deliveryItemsHavePhotos: false,
    onlineOrderingWorks: false,
    clickToCall: true,
    quoteForm: false,
    repliesFast: false
  }),
  buildAudit({
    businessName: "Summit Air & Heat",
    city: "Plano, TX",
    industry: "HVAC",
    websiteStatus: "modern",
    mobileFriendly: true,
    loadsFast: true,
    hasSsl: true,
    gbpClaimed: true,
    gbpHours: true,
    gbpPhotos: true,
    gbpDescription: true,
    gbpPrimaryCategory: true,
    hoursAccurate: true,
    phoneAccurate: true,
    addressAccurate: true,
    servicesAccurate: true,
    averageRating: 4.8,
    reviewCount: 84,
    mapsTopThree: true,
    clickToCall: true,
    quoteForm: true,
    repliesFast: true
  })
];
